name: OctoGuide

on:
  discussion:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - deleted
      - edited
  issue_comment:
    types:
      - created
      - deleted
      - edited
  issues:
    types:
      - edited
      - opened
  pull_request_review_comment:
    types:
      - created
      - deleted
      - edited
  pull_request_target:
    types:
      - edited
      - opened

permissions:
  discussions: write
  issues: write
  pull-requests: write

jobs:
  octoguide:
    if: ${{ !endsWith(github.actor, '[bot]') && !contains(github.event.pull_request.labels.*.name, 'autorelease') }}
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/octoguide@88dff3e0dc0e241123b357f783cf4528eea50529 # 0.21.9
        with:
          config: strict
          github-token: ${{ secrets.GITHUB_TOKEN }}
